import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Form from "../components/Form";
import USGSDataType from "../models/USGSDataType";

const Home: NextPage = () => {
  const [data, setData] = useState<USGSDataType | null>(null);
  const displayData = (data: USGSDataType | null): void => {
    setData(data);
  };

  return (
    <div className="flex flex-col justify-between items-center min-h-screen bg-slate-100">
      <Head>
        <title>Earthquake Map</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <div className="w-[90%] lg:w-1/2 mb-auto mt-6 py-6 bg-white rounded-md p-6 border-[1px] border-slate-300">
        <Form displayData={displayData} />
      </div>
      <Footer />
    </div>
  );
};

export default Home;
